### ISSUE TITLE
Adding Nationaal Wegen Bestand for the Netherlands

### ISSUE THREAD

**Issue by GigaaG** [Glodenox/wme-om#76]
The Nationaal Wegen Bestand (NWB) contains data from all road segments in the Netherlands, along with relevant information such as street name and place of residence.
I tried to add it myself by adding this line to your code:
`'3109': { id: 3109, title: 'Nationaal Wegen Bestand', url: 'https://geodata.nationaalgeoregister.nl/nwbwegen/wms', crs: 'EPSG:3857', bbox: new OL.Bounds(355925.15, 809871.56, 6563443.00, 7096825.88), format: 'image/png', area: 'NL', abstract: 'Nationaal Wegen Bestand met alle gegevens van de Nederlandse wegen', attribution: 'Nationaal Wegen Bestand', queryable: true, query_filters: [ applyAllTransformations ], default_layers: [ 'wegvakken' ], layers: { 'wegvakken': { title: 'Nationaal Wegen Bestand Wegvakken', queryable: true } } },` and I rearranged the row's in the query-results-table by:
`'3109': [ 'stt naam', 'wpsnaamnen' ],`
The layer will be added and is queryable, but the segments are almost invisible. See attachment. 
Can you add the layer properly by adding some style?
![Attachment](https://user-images.githubusercontent.com/33669464/77532048-6364ff80-6e94-11ea-8549-b60765f2b7ea.PNG)

**Comment by Glodenox** [comment]
There's not much I can change about how they generate their images for the WMS, I'm afraid. It does not seem like they have provided multiple styles from which can be chosen.

I did however look into manipulating pixel data after receiving images in #68, so that should be a solution for this issue. I could look at where the pixels can be found and adjust the bitmap so the lines become bigger.

**Comment by Glodenox** [comment]
This map was added in the latest version, including some improvements to how it gets displayed.

![Nationaal Wegen Bestand](https://user-images.githubusercontent.com/7704174/79498517-beb88680-8029-11ea-8a96-929980c2692a.jpg)
