### ISSUE TITLE
EV charging stations map

### ISSUE THREAD

**Issue by musa11971** [Glodenox/wme-om#96]
It would be nice to have a map that shows EV charging stations for the Netherlands (or even worldwide).

https://www.eco-movement.com/ could be a viable source

**Comment by Glodenox** [comment]
I'm afraid that specific resource is not available for free, so that's no option for me. While such a map would probably be possible, I'm not sure how useful it would be for adding these charging stations on the map.

A spreadsheet with permalinks to all charging stations is probably going to be more practical than this. And it would allow you to compare versions of the data over time to keep the information up to date. So I'd like to advise to look in that direction instead.
